#!/usr/bin/env sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
	CREATE USER "$NEXTCLOUD_ALICE_DB_USER" WITH PASSWORD '$NEXTCLOUD_ALICE_DB_PASSWORD';
	CREATE DATABASE "$NEXTCLOUD_ALICE_DB" OWNER "$NEXTCLOUD_ALICE_DB_USER";

	CREATE USER "$NEXTCLOUD_BOB_DB_USER" WITH PASSWORD '$NEXTCLOUD_BOB_DB_PASSWORD';
	CREATE DATABASE "$NEXTCLOUD_BOB_DB" OWNER "$NEXTCLOUD_BOB_DB_USER";
SQL
